<template>
    <div class="hello">
        <div class="card"   style="width: 18rem;">
          <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">example.</p>
              <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
    </div>
  </template> 
  
  <script>
  export default {
    data () {
        return {
        }
    }
  }
  </script>

